@stock_api_HostAddress = http://localhost:5011

POST  {{stock_api_HostAddress}}/place-order
Content-Type: application/json

{
    "id":"{{$guid}}",
    "lines":[
        {
            "itemId":1,
            "warehouseId":1,
            "quantity":1
        }
    ]
}
###
