@stock_api_HostAddress = http://localhost:5011

PUT  {{stock_api_HostAddress}}/place-order/{{$guid}}
Content-Type: application/json


[
    {
        "itemId":1,
        "warehouseId":1,
        "quantity":1
    }
]
###
