// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace stock_api.Migrations
{
    [DbContext(typeof(StockApiDataContext))]
    [Migration("20251004215202_AddedCheckAndTriggers")]
    partial class AddedCheckAndTriggers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("OrderLine", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("OrderId", "ItemId", "WarehouseId")
                        .HasName("pk_order_lines");

                    b.ToTable("order_lines", null, t =>
                        {
                            t.HasTrigger("LC_TRIGGER_AFTER_INSERT_ORDERLINE");
                        });

                    b.HasAnnotation("LC_TRIGGER_AFTER_INSERT_ORDERLINE", "CREATE FUNCTION \"LC_TRIGGER_AFTER_INSERT_ORDERLINE\"() RETURNS trigger as $LC_TRIGGER_AFTER_INSERT_ORDERLINE$\r\nBEGIN\r\n  UPDATE \"stock\"\r\n  SET \"reserved\" = \"stock\".\"reserved\" + NEW.\"quantity\"\r\n  WHERE \"stock\".\"item_id\" = NEW.\"item_id\" AND \"stock\".\"warehouse_id\" = NEW.\"warehouse_id\";\r\nRETURN NEW;\r\nEND;\r\n$LC_TRIGGER_AFTER_INSERT_ORDERLINE$ LANGUAGE plpgsql;\r\nCREATE TRIGGER LC_TRIGGER_AFTER_INSERT_ORDERLINE AFTER INSERT\r\nON \"order_lines\"\r\nFOR EACH ROW EXECUTE PROCEDURE \"LC_TRIGGER_AFTER_INSERT_ORDERLINE\"();");
                });

            modelBuilder.Entity("Stock", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("Reserved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved");

                    b.HasKey("ItemId", "WarehouseId")
                        .HasName("pk_stock");

                    b.ToTable("stock", null, t =>
                        {
                            t.HasCheckConstraint("check_stock", "quantity >= reserved");
                        });
                });

            modelBuilder.Entity("OrderLine", b =>
                {
                    b.HasOne("Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_lines_orders_order_id");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
