// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace stock_api.Migrations
{
    [DbContext(typeof(StockApiDataContext))]
    [Migration("20251104143611_SqlServer")]
    partial class SqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderLine", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ItemId", "WarehouseId");

                    b.ToTable("OrderLines", t =>
                        {
                            t.HasTrigger("LC_TRIGGER_AFTER_INSERT_ORDERLINE");
                        });

                    b
                        .HasAnnotation("LC_TRIGGER_AFTER_INSERT_ORDERLINE", "CREATE TRIGGER LC_TRIGGER_AFTER_INSERT_ORDERLINE ON \"OrderLines\" AFTER Insert AS\r\nBEGIN\r\n  DECLARE @NewQuantity INT, @NewItemId INT, @NewWarehouseId INT\r\n  DECLARE InsertedOrderLineCursor CURSOR LOCAL FOR SELECT Quantity, ItemId, WarehouseId FROM Inserted\r\n  OPEN InsertedOrderLineCursor\r\n  FETCH NEXT FROM InsertedOrderLineCursor INTO @NewQuantity, @NewItemId, @NewWarehouseId\r\n  WHILE @@FETCH_STATUS = 0\r\n  BEGIN\r\n    UPDATE \"Stock\"\r\n    SET \"Reserved\" = \"Stock\".\"Reserved\" + @NewQuantity\r\n    WHERE \"Stock\".\"ItemId\" = @NewItemId AND \"Stock\".\"WarehouseId\" = @NewWarehouseId;\r\n  FETCH NEXT FROM InsertedOrderLineCursor INTO @NewQuantity, @NewItemId, @NewWarehouseId\r\n  END\r\n  CLOSE InsertedOrderLineCursor DEALLOCATE InsertedOrderLineCursor\r\nEND")
                        .HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Stock", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Reserved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ItemId", "WarehouseId");

                    b.ToTable("Stock", t =>
                        {
                            t.HasCheckConstraint("check_stock", "Quantity >= Reserved");
                        });
                });

            modelBuilder.Entity("OrderLine", b =>
                {
                    b.HasOne("Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
