// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace stock_api.Migrations
{
    [DbContext(typeof(StockApiDataContext))]
    partial class StockApiDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<int>>("ItemIds")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("item_ids");

                    b.PrimitiveCollection<List<int>>("Quantities")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("quantities");

                    b.PrimitiveCollection<List<int>>("WarehouseIds")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("warehouse_ids");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasTrigger("LC_TRIGGER_AFTER_INSERT_ORDER");
                        });

                    b.HasAnnotation("LC_TRIGGER_AFTER_INSERT_ORDER", "CREATE FUNCTION \"LC_TRIGGER_AFTER_INSERT_ORDER\"() RETURNS trigger as $LC_TRIGGER_AFTER_INSERT_ORDER$\r\nBEGIN\r\n      UPDATE stock\r\n    SET reserved = reserved + x.q\r\n    FROM (\r\n        SELECT s.ctid, l.q\r\n        FROM stock s \r\n        JOIN unnest(NEW.\"item_ids\",NEW.\"warehouse_ids\",NEW.\"quantities\") AS l(i,w,q)\r\n            on (s.item_id, s.warehouse_id) = (l.i,l.w)\r\n        FOR NO KEY UPDATE\r\n    ) x\r\n    WHERE stock.ctid = x.ctid;\r\nRETURN NEW;\r\nEND;\r\n$LC_TRIGGER_AFTER_INSERT_ORDER$ LANGUAGE plpgsql;\r\nCREATE TRIGGER LC_TRIGGER_AFTER_INSERT_ORDER AFTER INSERT\r\nON \"orders\"\r\nFOR EACH ROW EXECUTE PROCEDURE \"LC_TRIGGER_AFTER_INSERT_ORDER\"();");
                });

            modelBuilder.Entity("Stock", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("Reserved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved");

                    b.HasKey("ItemId", "WarehouseId")
                        .HasName("pk_stock");

                    b.ToTable("stock", null, t =>
                        {
                            t.HasCheckConstraint("check_stock", "quantity >= reserved");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
